# resolve_ros_deps.cmake
#
# Input:
# - AMENT_XMAKE_ROS_PACKAGES: semicolon-separated package names
# - AMENT_XMAKE_OUTPUT: output lua manifest file path
#
# Output file format:
# return {
#   include_dirs = {...},
#   compile_definitions = {...},
#   link_flags = {...},
#   rpath_dirs = {...},
# }

if(NOT DEFINED AMENT_XMAKE_ROS_PACKAGES OR "${AMENT_XMAKE_ROS_PACKAGES}" STREQUAL "")
  message(FATAL_ERROR "AMENT_XMAKE_ROS_PACKAGES is required")
endif()
if(NOT DEFINED AMENT_XMAKE_OUTPUT OR "${AMENT_XMAKE_OUTPUT}" STREQUAL "")
  message(FATAL_ERROR "AMENT_XMAKE_OUTPUT is required")
endif()

set(_pkgs "${AMENT_XMAKE_ROS_PACKAGES}")
set(_include_dirs)
set(_compile_definitions)
set(_link_options)
set(_library_files)
set(_library_names)
set(_library_dirs)
set(_visited_targets)

macro(_append_unique _list_name _value)
  if(NOT "${_value}" STREQUAL "")
    list(FIND ${_list_name} "${_value}" _idx)
    if(_idx EQUAL -1)
      list(APPEND ${_list_name} "${_value}")
    endif()
  endif()
endmacro()

macro(_append_many_unique _list_name)
  foreach(_val IN LISTS ARGN)
    _append_unique(${_list_name} "${_val}")
  endforeach()
endmacro()

macro(_resolve_link_item _item)
  if("${_item}" STREQUAL "")
    return()
  endif()

  set(_item_eval "${_item}")
  string(REGEX MATCH "^\\$<TARGET_NAME_IF_EXISTS:([^>]+)>$" _m_target_if_exists "${_item_eval}")
  if(_m_target_if_exists)
    set(_tgt "${CMAKE_MATCH_1}")
    if(TARGET "${_tgt}")
      _resolve_target("${_tgt}")
    endif()
    return()
  endif()

  string(REGEX MATCH "^\\$<LINK_ONLY:([^>]+)>$" _m_link_only "${_item_eval}")
  if(_m_link_only)
    set(_inner "${CMAKE_MATCH_1}")
    _resolve_link_item("${_inner}")
    return()
  endif()

  if("${_item_eval}" MATCHES "^\\$<")
    return()
  endif()

  if(TARGET "${_item_eval}")
    _resolve_target("${_item_eval}")
    return()
  endif()

  if(IS_ABSOLUTE "${_item_eval}")
    _append_unique(_library_files "${_item_eval}")
    get_filename_component(_libdir "${_item_eval}" DIRECTORY)
    _append_unique(_library_dirs "${_libdir}")
    return()
  endif()

  string(REGEX MATCH "^-L(.+)$" _m_libdir "${_item_eval}")
  if(_m_libdir)
    _append_unique(_library_dirs "${CMAKE_MATCH_1}")
    return()
  endif()

  string(REGEX MATCH "^-l(.+)$" _m_libname "${_item_eval}")
  if(_m_libname)
    _append_unique(_library_names "${CMAKE_MATCH_1}")
    return()
  endif()

  if("${_item_eval}" MATCHES "^-")
    _append_unique(_link_options "${_item_eval}")
    return()
  endif()

  _append_unique(_library_names "${_item_eval}")
endmacro()

macro(_resolve_target _target_name)
  list(FIND _visited_targets "${_target_name}" _seen)
  if(NOT _seen EQUAL -1)
    return()
  endif()
  list(APPEND _visited_targets "${_target_name}")

  get_target_property(_incs "${_target_name}" INTERFACE_INCLUDE_DIRECTORIES)
  if(_incs AND NOT "${_incs}" STREQUAL "_incs-NOTFOUND")
    foreach(_inc IN LISTS _incs)
      if(NOT "${_inc}" MATCHES "^\\$<")
        _append_unique(_include_dirs "${_inc}")
      endif()
    endforeach()
  endif()

  get_target_property(_defs "${_target_name}" INTERFACE_COMPILE_DEFINITIONS)
  if(_defs AND NOT "${_defs}" STREQUAL "_defs-NOTFOUND")
    foreach(_def IN LISTS _defs)
      if(NOT "${_def}" MATCHES "^\\$<")
        _append_unique(_compile_definitions "${_def}")
      endif()
    endforeach()
  endif()

  get_target_property(_opts "${_target_name}" INTERFACE_LINK_OPTIONS)
  if(_opts AND NOT "${_opts}" STREQUAL "_opts-NOTFOUND")
    foreach(_opt IN LISTS _opts)
      if(NOT "${_opt}" MATCHES "^\\$<")
        _append_unique(_link_options "${_opt}")
      endif()
    endforeach()
  endif()

  set(_loc "")
  foreach(_cfg RELEASE RELWITHDEBINFO MINSIZEREL DEBUG NOCONFIG)
    get_target_property(_cand "${_target_name}" "IMPORTED_LOCATION_${_cfg}")
    if(_cand AND EXISTS "${_cand}")
      set(_loc "${_cand}")
      break()
    endif()
  endforeach()
  if("${_loc}" STREQUAL "")
    get_target_property(_cand "${_target_name}" IMPORTED_LOCATION)
    if(_cand AND EXISTS "${_cand}")
      set(_loc "${_cand}")
    endif()
  endif()
  if(NOT "${_loc}" STREQUAL "")
    _append_unique(_library_files "${_loc}")
    get_filename_component(_libdir "${_loc}" DIRECTORY)
    _append_unique(_library_dirs "${_libdir}")
  endif()

  get_target_property(_links "${_target_name}" INTERFACE_LINK_LIBRARIES)
  if(_links AND NOT "${_links}" STREQUAL "_links-NOTFOUND")
    foreach(_item IN LISTS _links)
      _resolve_link_item("${_item}")
    endforeach()
  endif()
endmacro()

foreach(_pkg IN LISTS _pkgs)
  find_package("${_pkg}" REQUIRED CONFIG)

  if(DEFINED ${_pkg}_INCLUDE_DIRS)
    _append_many_unique(_include_dirs ${${_pkg}_INCLUDE_DIRS})
  endif()
  if(DEFINED ${_pkg}_DEFINITIONS)
    _append_many_unique(_compile_definitions ${${_pkg}_DEFINITIONS})
  endif()
  if(DEFINED ${_pkg}_LINK_FLAGS)
    _append_many_unique(_link_options ${${_pkg}_LINK_FLAGS})
  endif()

  if(DEFINED ${_pkg}_TARGETS)
    foreach(_tgt IN LISTS ${_pkg}_TARGETS)
      if(TARGET "${_tgt}")
        _resolve_target("${_tgt}")
      endif()
    endforeach()
  endif()

  if(DEFINED ${_pkg}_LIBRARIES)
    foreach(_lib IN LISTS ${_pkg}_LIBRARIES)
      _resolve_link_item("${_lib}")
    endforeach()
  endif()
endforeach()

set(_link_flags)
foreach(_dir IN LISTS _library_dirs)
  _append_unique(_link_flags "-L${_dir}")
endforeach()
foreach(_file IN LISTS _library_files)
  _append_unique(_link_flags "${_file}")
endforeach()
foreach(_name IN LISTS _library_names)
  if("${_name}" MATCHES "^-")
    _append_unique(_link_flags "${_name}")
  else()
    _append_unique(_link_flags "-l${_name}")
  endif()
endforeach()
foreach(_opt IN LISTS _link_options)
  _append_unique(_link_flags "${_opt}")
endforeach()

get_filename_component(_outdir "${AMENT_XMAKE_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_outdir}")

function(_lua_escape _input _output_var)
  set(_v "${_input}")
  string(REPLACE "\\" "\\\\" _v "${_v}")
  string(REPLACE "\"" "\\\"" _v "${_v}")
  set(${_output_var} "${_v}" PARENT_SCOPE)
endfunction()

function(_write_lua_list _file _name _list_var)
  file(APPEND "${_file}" "  ${_name} = {\n")
  foreach(_item IN LISTS ${_list_var})
    _lua_escape("${_item}" _escaped)
    file(APPEND "${_file}" "    \"${_escaped}\",\n")
  endforeach()
  file(APPEND "${_file}" "  },\n")
endfunction()

file(WRITE "${AMENT_XMAKE_OUTPUT}" "return {\n")
_write_lua_list("${AMENT_XMAKE_OUTPUT}" "include_dirs" _include_dirs)
_write_lua_list("${AMENT_XMAKE_OUTPUT}" "compile_definitions" _compile_definitions)
_write_lua_list("${AMENT_XMAKE_OUTPUT}" "link_flags" _link_flags)
_write_lua_list("${AMENT_XMAKE_OUTPUT}" "rpath_dirs" _library_dirs)
file(APPEND "${AMENT_XMAKE_OUTPUT}" "}\n")
