name: ci

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke
        run: |
          test -f package.xml
          test -f CMakeLists.txt
          test -f xmake/rules/ament_xmake/package.lua
